# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - docker-hello

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4d07d866339d48b4ae34911966989dcf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_59fdd6a06ee94a5d95394f7e8f437abd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4d07d866339d48b4ae34911966989dcf }}/helloworld:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'docker-hello'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dc1ab761dd8244b48986bb7e69ea4c1f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4d07d866339d48b4ae34911966989dcf }}/helloworld:${{ github.sha }}'